export const REQUEST_COMMENT_LIST = 'REQUEST_COMMENT_LIST';
export const REQUEST_COMMENT_LIST_SUCCESS = 'REQUEST_COMMENT_LIST_SUCCESS';
export const REQUEST_COMMENT_LIST_FAILURE = 'REQUEST_COMMENT_LIST_FAILURE';
