export const REQUEST_POST_LIST = 'REQUEST_POST_LIST';
export const REQUEST_POST_LIST_SUCCESS = 'REQUEST_POST_LIST_SUCCESS';
export const REQUEST_POST_LIST_FAILURE = 'REQUEST_POST_LIST_FAILURE';

export const REQUEST_POST_CATEGORY = 'REQUEST_POST_CATEGORY';
